title: Page blanche
# email: praginel@free.fr
description: >-
  Site blanc
baseurl: "/comitesavoienwp"

# Build settings
theme: minima
lang: fr
exclude:
  # - VieuxSite/
  # - pdfs/
  # - images/
  - .gitignore
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bin/
