title: Water-polo AURA
email: praginel@free.fr
description: >-
  Site du water-polo de la région Auvergne-Rhône-Alpes
baseurl: "/comitesavoienwp"
url: "https://praginel.github.io/"
github_username:  praginel

# Build settings
theme: minima
lang: fr
plugins:
  - jekyll-feed
csv_reader:
  converters:
    - numeric
    - datetime
  headers: true
  encoding: utf-8
exclude:
  # - VieuxSite/
  # - pdfs/
  # - images/
  - .gitignore
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bin/
